import os
import sys
import glob
import json
import time
import requests
import pandas as pd
from datetime import datetime

# Reconfigure console output encoding to prevent Windows crash on non-ASCII characters
if hasattr(sys.stdout, 'reconfigure'):
    try:
        sys.stdout.reconfigure(encoding='utf-8', errors='backslashreplace')
    except:
        pass

# ══════════════════════════════════════════════════════════════════
#  Configuration & Environment Loader
# ══════════════════════════════════════════════════════════════════

BASE_DIR = os.path.dirname(os.path.abspath(__file__))
ENV_PATH = os.path.join(BASE_DIR, "googleDrive", "env")

def load_env_variables(env_path):
    env = {}
    if os.path.exists(env_path):
        with open(env_path, 'r', encoding='utf-8') as f:
            for line in f:
                line = line.strip()
                if line and not line.startswith('#'):
                    parts = line.split('=', 1)
                    if len(parts) == 2:
                        env[parts[0].strip()] = parts[1].strip()
    return env

ENV = load_env_variables(ENV_PATH)
TELEGRAM_BOT_TOKEN = ENV.get("TELEGRAM_BOT_TOKEN")
GROQ_API_KEY = ENV.get("GROQ_API_KEY")

if not TELEGRAM_BOT_TOKEN:
    print("❌ ERROR: TELEGRAM_BOT_TOKEN not found in googleDrive/env!")
    sys.exit(1)
if not GROQ_API_KEY:
    print("❌ ERROR: GROQ_API_KEY not found in googleDrive/env!")
    sys.exit(1)

# ══════════════════════════════════════════════════════════════════
#  Data Manager (Handles Lazy Loading & Auto-Reloading of CSV)
# ══════════════════════════════════════════════════════════════════

class SalesDataManager:
    def __init__(self):
        self.df = None
        self.df_mpo = None
        self.depots_list = []
        self.zones_list = []
        self.fm_ams_list = []
        self.loaded_csv_path = None
        self.last_mtime = 0
        
        # Load MPO mappings once
        self.load_mpo_mappings()
        # Initial load
        self.check_and_load_data()

    def load_mpo_mappings(self):
        mpo_code_xlsx = os.path.join(BASE_DIR, "archive", "recent", "mpo_code.xlsx")
        if os.path.exists(mpo_code_xlsx):
            try:
                self.df_mpo = pd.read_excel(mpo_code_xlsx)
                self.depots_list = [str(x) for x in self.df_mpo['DEPOT'].dropna().unique()]
                self.zones_list = [str(x) for x in self.df_mpo['ZONE'].dropna().unique()]
                self.fm_ams_list = [str(x) for x in self.df_mpo['FM/AM'].dropna().unique()]
                print(f"✓ Loaded {len(self.df_mpo)} MPO mappings (Depots: {len(self.depots_list)}, Zones: {len(self.zones_list)}).")
            except Exception as e:
                print(f"⚠ Warning: Failed to load mpo_code.xlsx: {e}")
        else:
            print("⚠ Warning: mpo_code.xlsx not found at archive/recent/mpo_code.xlsx")

    def get_latest_csv_path(self):
        csv_files = glob.glob(os.path.join(BASE_DIR, "01.1_Date_wise_Customer_wise_Product_wise_Net_Sales_Extracted_Data_*.csv"))
        if not csv_files:
            return None
        # Sort by modification time to get the latest one
        csv_files.sort(key=os.path.getmtime, reverse=True)
        return csv_files[0]

    def check_and_load_data(self):
        latest_csv = self.get_latest_csv_path()
        if not latest_csv:
            print("⚠ Warning: No 01.1 Date-wise CSV file found in root yet.")
            return False
            
        mtime = os.path.getmtime(latest_csv)
        
        # Reload if not loaded yet, or if file has been modified (e.g. newly generated by admin)
        if self.df is None or latest_csv != self.loaded_csv_path or mtime > self.last_mtime:
            print(f"🔄 Loading/Reloading sales data: {os.path.basename(latest_csv)}...")
            t0 = time.time()
            try:
                df_raw = pd.read_csv(latest_csv)
                
                # Merge MPO mapping data at load time if available
                if self.df_mpo is not None:
                    df_mpo_temp = self.df_mpo.copy()
                    df_mpo_temp.rename(columns={'DEPOT': 'DEPOT_mpo', 'MPO CODE': 'MPO_CODE_mpo'}, inplace=True)
                    df_merged = pd.merge(df_raw, df_mpo_temp, left_on=['Depot', 'MPO_Code'], right_on=['DEPOT_mpo', 'MPO_CODE_mpo'], how='left')
                    
                    # Apply fallback depot to zone mapping for unmatched MPOs
                    depot_to_zone = self.df_mpo.groupby('DEPOT')['ZONE'].first().to_dict()
                    df_merged['ZONE'] = df_merged['ZONE'].fillna(df_merged['Depot'].map(depot_to_zone))
                    self.df = df_merged
                else:
                    self.df = df_raw
                    
                self.loaded_csv_path = latest_csv
                self.last_mtime = mtime
                print(f"✓ Loaded {len(self.df):,} records in {time.time() - t0:.2f} seconds.")
                return True
            except Exception as e:
                print(f"❌ Error loading CSV: {e}")
                return False
        return True

    def get_mpo_list_for_depot(self, depot_name):
        mpo_list = []
        if self.df_mpo is not None and depot_name:
            df_depot = self.df_mpo[self.df_mpo['DEPOT'].str.upper() == depot_name.upper()]
            for idx, row in df_depot.iterrows():
                if pd.notna(row['MARKET']) and pd.notna(row['MPO CODE']):
                    mpo_list.append({
                        "MARKET": str(row['MARKET']).strip(),
                        "MPO CODE": str(row['MPO CODE']).strip()
                    })
        return mpo_list

# Instantiate Data Manager
DATA_MANAGER = SalesDataManager()

# ══════════════════════════════════════════════════════════════════
#  Chat Session Context Manager (For follow-up questions)
# ══════════════════════════════════════════════════════════════════

class ChatSessionManager:
    def __init__(self):
        self.sessions = {}  # chat_id -> list of message dicts

    def get_history(self, chat_id):
        if chat_id not in self.sessions:
            self.sessions[chat_id] = []
        return self.sessions[chat_id]

    def add_message(self, chat_id, role, content):
        history = self.get_history(chat_id)
        history.append({"role": role, "content": content})
        # Keep only the last 6 messages (3 turns) to prevent context bloat
        if len(history) > 6:
            self.sessions[chat_id] = history[-6:]

    def clear_session(self, chat_id):
        self.sessions[chat_id] = []

# Instantiate Session Manager
SESSION_MANAGER = ChatSessionManager()

# ══════════════════════════════════════════════════════════════════
#  Groq AI Intent Parser (Context Aware & Upgraded)
# ══════════════════════════════════════════════════════════════════

def extract_depot_with_ai(query_text, history_messages=None):
    url = "https://api.groq.com/openai/v1/chat/completions"
    headers = {
        "Authorization": f"Bearer {GROQ_API_KEY}",
        "Content-Type": "application/json"
    }
    
    system_prompt = f"""Identify which depot the user is talking about. 
The valid depots are: {', '.join(DATA_MANAGER.depots_list)}.
Map common variations (e.g. 'Bariahsal' or 'Barisal' -> 'BARISHAL', 'Chittagong' -> 'CHATTOGRAM', 'Comilla' -> 'CUMILLA', 'Faridpur Zone' -> 'FARIDPUR', 'Dhaka 1' -> 'DHAKA-1', 'Dhaka 2' -> 'DHAKA-2').

This is a chat context. If the user's latest query does not mention a depot, but the previous conversation did, you should refer to the history to identify the depot.
Return a JSON object with a single key 'depot' (string in uppercase, or null if not mentioned and cannot be inferred)."""

    # Build messages with history
    messages = [{"role": "system", "content": system_prompt}]
    if history_messages:
        for msg in history_messages[:-1]:
            if msg["role"] == "assistant":
                try:
                    js = json.loads(msg["content"])
                    messages.append({"role": "assistant", "content": f"Active Depot: {js.get('depot')}"})
                except:
                    messages.append(msg)
            else:
                messages.append(msg)
                
    messages.append({"role": "user", "content": f"Query: {query_text}"})

    data = {
        "model": "llama-3.3-70b-versatile",
        "messages": messages,
        "temperature": 0.0,
        "response_format": {"type": "json_object"}
    }
    
    try:
        r = requests.post(url, headers=headers, json=data, timeout=15)
        r.raise_for_status()
        result = r.json()
        return json.loads(result["choices"][0]["message"]["content"]).get("depot")
    except Exception as e:
        print(f"  [AI] Error detecting depot: {e}")
        return None

def extract_query_intent(query_text, depot, mpo_list, history_messages=None):
    url = "https://api.groq.com/openai/v1/chat/completions"
    headers = {
        "Authorization": f"Bearer {GROQ_API_KEY}",
        "Content-Type": "application/json"
    }
    
    mpo_context = ""
    if mpo_list:
        mpo_context = "Valid markets and MPO Codes for this Depot:\n"
        for m in mpo_list:
            mpo_context += f"- Market: {m['MARKET']} -> MPO Code: {m['MPO CODE']}\n"
            
    system_prompt = f"""You are an AI assistant designed to extract filtering and aggregation parameters from a natural language query for a sales database.
Here is the context for the current Depot '{depot or "Unknown"}':
{mpo_context}

Valid Zones (e.g. 'FRD' is Faridpur Zone, 'BARI' is Barishal Zone): {', '.join(DATA_MANAGER.zones_list)}
Some Example FM/AM Names: {', '.join(DATA_MANAGER.fm_ams_list[:20])}

The database fields to extract are:
- month: Format YYYY-MM. (e.g. 'january', 'jan' -> '2026-01', 'April', 'apr' -> '2026-04', 'May' -> '2026-05', etc. Assume the year is 2026).
- product_brand: E.g. 'ALAGRA', 'MOKAST' (brand name in uppercase).
- product_code: E.g. 'ALK1', 'MON1' (code if explicitly mentioned).
- mpo_code: Match from MPO code list, or if explicitly mentioned.
- zone: Match to a valid zone code (e.g. 'FRD', 'BARI', 'COM').
- fm_am: The name of the Field Manager / Area Manager.
- market: The name of the market mentioned.
- vacant_only: boolean (true if user asks for vacant markets, vacant MPOs, or vacant forces. Otherwise false).

Aggregation fields:
- group_by: Set to "month" if the user asks for a breakdown by month (e.g. 'kon maase koto sale hoise', 'month-wise', 'monthly sales'). Set to "market" if they ask for market-wise breakdown. Set to "fm_am" if they ask for manager-wise. Set to "mpo_code" if they ask for MPO-wise. Otherwise null.

This is a chat conversation. If the user's latest query is a follow-up, inherit parameters from previous assistant's JSON responses in the history, unless explicitly changed.

Return ONLY a JSON object with keys:
- depot (string, or null)
- month (string 'YYYY-MM', or null)
- product_brand (string, or null)
- product_code (string, or null)
- mpo_code (string, or null)
- zone (string, or null)
- fm_am (string, or null)
- market (string, or null)
- vacant_only (boolean)
- group_by (string: "month", "market", "fm_am", "mpo_code", or null)

Do not include any explanation or markdown formatting, return raw JSON string."""

    # Build messages with history
    messages = [{"role": "system", "content": system_prompt}]
    if history_messages:
        for msg in history_messages[:-1]:
            messages.append(msg)
    messages.append({"role": "user", "content": f"Query: {query_text}"})

    data = {
        "model": "llama-3.3-70b-versatile",
        "messages": messages,
        "temperature": 0.0,
        "response_format": {"type": "json_object"}
    }
    
    try:
        r = requests.post(url, headers=headers, json=data, timeout=20)
        r.raise_for_status()
        result = r.json()
        return json.loads(result["choices"][0]["message"]["content"])
    except Exception as e:
        print(f"  [AI] Error extracting query intent: {e}")
        return {}

# ══════════════════════════════════════════════════════════════════
#  Query Processor (Filters Data & Formats Response)
# ══════════════════════════════════════════════════════════════════

def process_sales_query(chat_id, query_text):
    # Ensure latest data is loaded
    DATA_MANAGER.check_and_load_data()
    
    if DATA_MANAGER.df is None:
        return "❌ Error: Sales database file is not loaded or not found. Please ask the Admin to run the pipeline first."
        
    print(f"\nProcessing query for Chat {chat_id}: '{query_text}'")
    
    # Get history for this session
    history = SESSION_MANAGER.get_history(chat_id)
    # Temporary append user query for the detection step
    temp_msg = {"role": "user", "content": query_text}
    history.append(temp_msg)
    
    # 1. Detect Depot (Context Aware)
    depot = extract_depot_with_ai(query_text, history)
    print(f"  Depot detected: {depot}")
    
    # 2. Get markets list for this depot
    mpo_list = DATA_MANAGER.get_mpo_list_for_depot(depot)
    
    # 3. Extract details using AI with MPO context and full history
    intent = extract_query_intent(query_text, depot, mpo_list, history)
    print(f"  Extracted Intent: {json.dumps(intent)}")
    
    # Update the depot if intent found a different one
    if intent.get("depot"):
        depot = intent["depot"]
        
    # Standardize intent by injecting the detected depot
    intent["depot"] = depot
    
    # Store this turn in history (we remove the temporary user message and add structured ones)
    history.pop()  # remove temp user message
    SESSION_MANAGER.add_message(chat_id, "user", query_text)
    SESSION_MANAGER.add_message(chat_id, "assistant", json.dumps(intent))
    
    month = intent.get("month")
    product_brand = intent.get("product_brand")
    product_code = intent.get("product_code")
    mpo_code = intent.get("mpo_code")
    zone = intent.get("zone")
    fm_am = intent.get("fm_am")
    market = intent.get("market")
    vacant_only = intent.get("vacant_only")
    group_by = intent.get("group_by")
    
    # 4. Filter DataFrame
    filtered_df = DATA_MANAGER.df.copy()
    
    if depot:
        filtered_df = filtered_df[filtered_df['Depot'].str.upper() == depot.upper()]
    if zone:
        filtered_df = filtered_df[filtered_df['ZONE'].str.upper() == zone.upper()]
    if month:
        filtered_df = filtered_df[filtered_df['Month'] == month]
    if product_brand:
        filtered_df = filtered_df[filtered_df['Product_Name'].str.contains(product_brand, case=False, na=False)]
    if product_code:
        filtered_df = filtered_df[filtered_df['Product_Code'].str.upper() == product_code.upper()]
    if mpo_code:
        filtered_df = filtered_df[filtered_df['MPO_Code'].str.upper() == mpo_code.upper()]
    if fm_am:
        filtered_df = filtered_df[filtered_df['FM/AM'].str.contains(fm_am, case=False, na=False)]
    if market:
        filtered_df = filtered_df[filtered_df['MARKET'].str.contains(market, case=False, na=False)]
    if vacant_only:
        filtered_df = filtered_df[filtered_df['FM/AM'].str.contains('VACANT', case=False, na=False)]
        
    if filtered_df.empty:
        # Build friendly empty-result message
        filters = []
        if depot: filters.append(f"Depot: {depot}")
        if zone: filters.append(f"Zone: {zone}")
        if month: filters.append(f"Month: {month}")
        if product_brand: filters.append(f"Product: {product_brand}")
        if mpo_code: filters.append(f"MPO: {mpo_code}")
        if fm_am: filters.append(f"Manager: {fm_am}")
        if market: filters.append(f"Market: {market}")
        if vacant_only: filters.append("Vacant Markets Only")
        
        filter_str = ", ".join(filters) if filters else "No filters"
        return f"⚠️ *No records found matching your query.*\n\n*Applied Filters:* {filter_str}\n\nPlease verify your query details and try again."

    # 5. Build response Markdown message
    msg_lines = [
        "📊 *SALES REPORT SUMMARY*",
        "=========================================",
        f"🔍 *Query:* \"{query_text}\"",
        "",
        "📍 *Filter Details:*"
    ]
    
    if depot:
        msg_lines.append(f"▪️ *Depot:* {depot}")
    else:
        msg_lines.append("▪️ *Depot:* ALL")
        
    if zone:
        msg_lines.append(f"▪️ *Zone:* {zone}")
    if month:
        try:
            dt = datetime.strptime(month, "%Y-%m")
            msg_lines.append(f"▪️ *Month:* {dt.strftime('%B %Y')}")
        except:
            msg_lines.append(f"▪️ *Month:* {month}")
            
    if product_brand:
        msg_lines.append(f"▪️ *Product:* {product_brand}")
    if product_code:
        msg_lines.append(f"▪️ *Product Code:* {product_code}")
    if mpo_code:
        market_display = None
        if DATA_MANAGER.df_mpo is not None:
            mpo_match = DATA_MANAGER.df_mpo[
                (DATA_MANAGER.df_mpo['MPO CODE'].str.upper() == mpo_code.upper()) &
                (DATA_MANAGER.df_mpo['DEPOT'].str.upper() == (depot or "").upper())
            ]
            if not mpo_match.empty:
                market_display = mpo_match.iloc[0]['MARKET']
        mpo_info = f"{mpo_code}"
        if market_display:
            mpo_info += f" ({market_display})"
        msg_lines.append(f"▪️ *Market/MPO:* {mpo_info}")
        
    if fm_am:
        msg_lines.append(f"▪️ *Manager (FM/AM):* {fm_am}")
    if market and not mpo_code:
        msg_lines.append(f"▪️ *Market:* {market}")
    if vacant_only:
        msg_lines.append("▪️ *Forces:* VACANT ONLY")
        
    msg_lines.append("=========================================")

    # 6. Aggregation & Formatting
    if group_by:
        # Perform group by breakdown
        group_col = None
        group_label = ""
        
        if group_by == 'month':
            group_col = 'Month'
            group_label = 'Monthly breakdown'
        elif group_by == 'market':
            group_col = 'MARKET'
            group_label = 'Market-wise breakdown (Top 15)'
        elif group_by == 'fm_am':
            group_col = 'FM/AM'
            group_label = 'Manager-wise breakdown (Top 15)'
        elif group_by == 'mpo_code':
            group_col = 'MPO_Code'
            group_label = 'MPO-wise breakdown (Top 15)'
            
        if group_col in filtered_df.columns:
            # Group stats
            grouped = filtered_df.groupby(group_col).agg(
                box_sold=('Quantity', 'sum'),
                sales_amount=('Line_Amount', 'sum'),
                invoices=('Invoice_No', 'nunique'),
                customers=('Customer_ID', 'nunique')
            ).reset_index()
            
            # Sort order
            if group_by == 'month':
                # Chronological sort
                grouped = grouped.sort_values(by='Month')
            else:
                # Descending sales volume sort
                grouped = grouped.sort_values(by='box_sold', ascending=False).head(15)
                
            msg_lines.append(f"📈 *{group_label}:*")
            
            for idx, row in grouped.iterrows():
                col_val = row[group_col]
                # Format month name
                if group_by == 'month':
                    try:
                        dt = datetime.strptime(str(col_val), "%Y-%m")
                        col_val = dt.strftime("%b %Y")
                    except:
                        pass
                
                # Format amounts
                box_str = f"{row['box_sold']:,.2f} Boxes"
                amt_str = f"{row['sales_amount']:,.2f} TK"
                inv_str = f"{row['invoices']:,} Inv"
                cus_str = f"{row['customers']:,} Cus"
                
                msg_lines.append(f"▪️ *{col_val}:* {box_str} ({amt_str}, {inv_str}, {cus_str})")
            
            # Print grand total summary below
            total_qty = filtered_df['Quantity'].sum()
            total_amount = filtered_df['Line_Amount'].sum()
            msg_lines.extend([
                "-----------------------------------------",
                f"🧮 *Grand Total:* *{total_qty:,.2f} Boxes* ({total_amount:,.2f} TK)"
            ])
        else:
            msg_lines.append(f"⚠ Aggregation field '{group_by}' could not be matched to data columns.")
            
    else:
        # Standard grand totals output
        total_qty = filtered_df['Quantity'].sum()
        total_amount = filtered_df['Line_Amount'].sum()
        invoices = filtered_df['Invoice_No'].nunique()
        customers = filtered_df['Customer_ID'].nunique()
        
        msg_lines.extend([
            "📈 *Calculated Statistics:*",
            f"▪️ *Total Box Sold:* *{total_qty:,.2f}*",
            f"▪️ *Total Net Sales:* *{total_amount:,.2f} TK*",
            f"▪️ *Total Invoices:* *{invoices:,}*",
            f"▪️ *Unique Customers:* *{customers:,}*"
        ])
        
    msg_lines.append("=========================================")
    return "\n".join(msg_lines)

# ══════════════════════════════════════════════════════════════════
#  Telegram Bot Core & Long Polling Loop
# ══════════════════════════════════════════════════════════════════

def send_telegram_message(chat_id, text):
    url = f"https://api.telegram.org/bot{TELEGRAM_BOT_TOKEN}/sendMessage"
    payload = {
        "chat_id": chat_id,
        "text": text,
        "parse_mode": "Markdown"
    }
    try:
        r = requests.post(url, json=payload, timeout=15)
        r.raise_for_status()
    except Exception as e:
        print(f"❌ Error sending message to {chat_id}: {e}")

def handle_start_command(chat_id):
    SESSION_MANAGER.clear_session(chat_id)
    welcome_text = """👋 *Hello! I am the Alco Pharma Sales Query Bot.*

I can query the latest sales transaction report generated by the Admin and give you quick stats on demand.

ℹ️ *What you can ask me (Bangla or English):*
▪️ "january maase Bariahsal 1 Market e alagra koto box sale hoise"
▪️ "chattogram depot e may maase mokast koto invoice aar customer cilo"
▪️ "B001 mpo code er alagra total sales amount koto"
▪️ "Alagra kon maase koto sale hoise? Faridpur Zone e"

💬 *Note:* I remember the context of the chat! If you ask a follow-up question, I will keep your previous filters (like month or product) active!

To reset context and start fresh, type `/reset` or `/start`.

Just type your question below! 👇"""
    send_telegram_message(chat_id, welcome_text)

def handle_reset_command(chat_id):
    SESSION_MANAGER.clear_session(chat_id)
    send_telegram_message(chat_id, "🔄 *Chat context has been reset.* You can start a new query now.")

def main_loop():
    print("=" * 80)
    print("  TELEGRAM SALES QUERY BOT - RUNNING (LONG POLLING WITH METADATA MAPPING)")
    print("=" * 80)
    print(f"Bot Token: {TELEGRAM_BOT_TOKEN[:15]}...")
    if DATA_MANAGER.loaded_csv_path:
        print(f"Active Data File: {os.path.basename(DATA_MANAGER.loaded_csv_path)}")
    else:
        print("Active Data File: None (waiting for file generation)")
    print("Bot is listening for messages... Press Ctrl+C to exit.\n")
    
    offset = None
    
    while True:
        try:
            url = f"https://api.telegram.org/bot{TELEGRAM_BOT_TOKEN}/getUpdates"
            params = {"timeout": 30}
            if offset:
                params["offset"] = offset
                
            response = requests.get(url, params=params, timeout=35)
            if response.status_code != 200:
                print(f"⚠ Telegram API returned status {response.status_code}. Retrying...")
                time.sleep(5)
                continue
                
            updates = response.json().get("result", [])
            
            for update in updates:
                offset = update["update_id"] + 1
                
                if "message" not in update:
                    continue
                    
                message = update["message"]
                chat_id = message["chat"]["id"]
                user_info = message["chat"].get("username") or message["chat"].get("first_name") or "User"
                
                if "text" not in message:
                    continue
                    
                text = message["text"].strip()
                print(f"📩 Received message from {user_info} ({chat_id}): '{text}'")
                
                # Check for commands
                if text.startswith("/start") or text.startswith("/help"):
                    handle_start_command(chat_id)
                    continue
                elif text.startswith("/reset"):
                    handle_reset_command(chat_id)
                    continue
                
                # Process query
                send_telegram_message(chat_id, "⏳ *Processing your query... please wait.*")
                
                try:
                    response_text = process_sales_query(chat_id, text)
                except Exception as ex:
                    print(f"❌ Error processing query: {ex}")
                    response_text = "❌ *An error occurred while processing your query.* Please make sure the query format is correct."
                    
                send_telegram_message(chat_id, response_text)
                print(f"📤 Sent reply to {user_info} ({chat_id})")
                
        except KeyboardInterrupt:
            print("\nShutting down bot...")
            break
        except Exception as e:
            print(f"⚠ Loop Error: {e}")
            time.sleep(5)

if __name__ == "__main__":
    main_loop()
