import os
import sys
import glob
import json
import time
import requests
import pandas as pd
from datetime import datetime

# Reconfigure console output encoding to prevent Windows crash on non-ASCII characters
if hasattr(sys.stdout, 'reconfigure'):
    try:
        sys.stdout.reconfigure(encoding='utf-8', errors='backslashreplace')
    except:
        pass

# ══════════════════════════════════════════════════════════════════
#  Configuration & Environment Loader
# ══════════════════════════════════════════════════════════════════

BASE_DIR = os.path.dirname(os.path.abspath(__file__))
ENV_PATH = os.path.join(BASE_DIR, "googleDrive", "env")

def load_env_variables(env_path):
    env = {}
    if os.path.exists(env_path):
        with open(env_path, 'r', encoding='utf-8') as f:
            for line in f:
                line = line.strip()
                if line and not line.startswith('#'):
                    parts = line.split('=', 1)
                    if len(parts) == 2:
                        env[parts[0].strip()] = parts[1].strip()
    return env

ENV = load_env_variables(ENV_PATH)
TELEGRAM_BOT_TOKEN = ENV.get("TELEGRAM_BOT_TOKEN")
GROQ_API_KEY = ENV.get("GROQ_API_KEY")

if not TELEGRAM_BOT_TOKEN:
    print("❌ ERROR: TELEGRAM_BOT_TOKEN not found in googleDrive/env!")
    sys.exit(1)
if not GROQ_API_KEY:
    print("❌ ERROR: GROQ_API_KEY not found in googleDrive/env!")
    sys.exit(1)

# ══════════════════════════════════════════════════════════════════
#  Data Manager (Handles Lazy Loading & Auto-Reloading of CSV)
# ══════════════════════════════════════════════════════════════════

class SalesDataManager:
    def __init__(self):
        self.df = None
        self.df_mpo = None
        self.loaded_csv_path = None
        self.last_mtime = 0
        
        # Load MPO mappings once
        self.load_mpo_mappings()
        # Initial load
        self.check_and_load_data()

    def load_mpo_mappings(self):
        mpo_code_xlsx = os.path.join(BASE_DIR, "archive", "recent", "mpo_code.xlsx")
        if os.path.exists(mpo_code_xlsx):
            try:
                self.df_mpo = pd.read_excel(mpo_code_xlsx)
                print(f"✓ Loaded {len(self.df_mpo)} MPO mappings from: mpo_code.xlsx")
            except Exception as e:
                print(f"⚠ Warning: Failed to load mpo_code.xlsx: {e}")
        else:
            print("⚠ Warning: mpo_code.xlsx not found at archive/recent/mpo_code.xlsx")

    def get_latest_csv_path(self):
        csv_files = glob.glob(os.path.join(BASE_DIR, "01.1_Date_wise_Customer_wise_Product_wise_Net_Sales_Extracted_Data_*.csv"))
        if not csv_files:
            return None
        # Sort by modification time to get the latest one
        csv_files.sort(key=os.path.getmtime, reverse=True)
        return csv_files[0]

    def check_and_load_data(self):
        latest_csv = self.get_latest_csv_path()
        if not latest_csv:
            print("⚠ Warning: No 01.1 Date-wise CSV file found in root yet.")
            return False
            
        mtime = os.path.getmtime(latest_csv)
        
        # Reload if not loaded yet, or if file has been modified (e.g. newly generated by admin)
        if self.df is None or latest_csv != self.loaded_csv_path or mtime > self.last_mtime:
            print(f"🔄 Loading/Reloading sales data: {os.path.basename(latest_csv)}...")
            t0 = time.time()
            try:
                self.df = pd.read_csv(latest_csv)
                self.loaded_csv_path = latest_csv
                self.last_mtime = mtime
                print(f"✓ Loaded {len(self.df):,} records in {time.time() - t0:.2f} seconds.")
                return True
            except Exception as e:
                print(f"❌ Error loading CSV: {e}")
                return False
        return True

    def get_mpo_list_for_depot(self, depot_name):
        mpo_list = []
        if self.df_mpo is not None and depot_name:
            df_depot = self.df_mpo[self.df_mpo['DEPOT'].str.upper() == depot_name.upper()]
            for idx, row in df_depot.iterrows():
                if pd.notna(row['MARKET']) and pd.notna(row['MPO CODE']):
                    mpo_list.append({
                        "MARKET": str(row['MARKET']).strip(),
                        "MPO CODE": str(row['MPO CODE']).strip()
                    })
        return mpo_list

# Instantiate Data Manager
DATA_MANAGER = SalesDataManager()

# ══════════════════════════════════════════════════════════════════
#  Groq AI Intent Parser
# ══════════════════════════════════════════════════════════════════

def extract_depot_with_ai(query_text):
    url = "https://api.groq.com/openai/v1/chat/completions"
    headers = {
        "Authorization": f"Bearer {GROQ_API_KEY}",
        "Content-Type": "application/json"
    }
    
    system_prompt = """Identify which depot the user is talking about. 
The valid depots are: BARISHAL, CHATTOGRAM, CUMILLA, DHAKA-1, DHAKA-2, FARIDPUR, JASHORE, MYMENSINGH, RAJSHAHI, RANGPUR.
Map common variations (e.g. 'Bariahsal' or 'Barisal' -> 'BARISHAL', 'Chittagong' -> 'CHATTOGRAM', 'Comilla' -> 'CUMILLA', 'Dhaka 1' -> 'DHAKA-1', 'Dhaka 2' -> 'DHAKA-2', 'Faridpur' -> 'FARIDPUR', 'Jessore' -> 'JASHORE', 'Mymensingh' -> 'MYMENSINGH', 'Rajshahi' -> 'RAJSHAHI', 'Rangpur' -> 'RANGPUR').
Return a JSON object with a single key 'depot' (string in uppercase, or null if not mentioned)."""

    data = {
        "model": "llama-3.3-70b-versatile",
        "messages": [
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": f"Query: {query_text}"}
        ],
        "temperature": 0.0,
        "response_format": {"type": "json_object"}
    }
    
    try:
        r = requests.post(url, headers=headers, json=data, timeout=15)
        r.raise_for_status()
        result = r.json()
        return json.loads(result["choices"][0]["message"]["content"]).get("depot")
    except Exception as e:
        print(f"  [AI] Error detecting depot: {e}")
        return None

def extract_query_intent(query_text, depot, mpo_list):
    url = "https://api.groq.com/openai/v1/chat/completions"
    headers = {
        "Authorization": f"Bearer {GROQ_API_KEY}",
        "Content-Type": "application/json"
    }
    
    mpo_context = ""
    if mpo_list:
        mpo_context = "Valid markets and MPO Codes for this Depot:\n"
        for m in mpo_list:
            mpo_context += f"- Market: {m['MARKET']} -> MPO Code: {m['MPO CODE']}\n"
            
    system_prompt = f"""You are an AI assistant designed to extract filtering parameters from a natural language query for a sales database.
Here is the context for the current Depot '{depot or "Unknown"}':
{mpo_context}

The database fields to extract are:
- Month: Format YYYY-MM. (e.g. 'january', 'jan' -> '2026-01', 'April', 'apr' -> '2026-04', 'May' -> '2026-05', etc. Assume the year is 2026 unless specified otherwise).
- Product_Name: E.g. 'ALAGRA', 'MOKAST'. Extract the base brand name in uppercase (e.g. 'alagra' -> 'ALAGRA', 'mokast' -> 'MOKAST').
- MPO_Code: Based on the market/MPO mentioned in the query, find the closest matching MPO Code from the list above. If the query mentions 'Barishal 1 Market' and the list has 'BSHL. MEDICAL-1 -> B001', select 'B001'.
- Customer_Name: Extract if a specific customer name or pharmacy is mentioned in the query.

Return ONLY a JSON object with keys:
- month (string 'YYYY-MM', or null)
- product_brand (string in uppercase like 'ALAGRA', 'MOKAST', or null)
- mpo_code (string from the provided list, or null)
- customer_name (string, or null)

Do not include any explanation or markdown formatting, return raw JSON string."""

    data = {
        "model": "llama-3.3-70b-versatile",
        "messages": [
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": f"Query: {query_text}"}
        ],
        "temperature": 0.0,
        "response_format": {"type": "json_object"}
    }
    
    try:
        r = requests.post(url, headers=headers, json=data, timeout=20)
        r.raise_for_status()
        result = r.json()
        return json.loads(result["choices"][0]["message"]["content"])
    except Exception as e:
        print(f"  [AI] Error extracting query intent: {e}")
        return {}

# ══════════════════════════════════════════════════════════════════
#  Query Processor (Filters Data & Formats Response)
# ══════════════════════════════════════════════════════════════════

def process_sales_query(query_text):
    # Ensure latest data is loaded
    DATA_MANAGER.check_and_load_data()
    
    if DATA_MANAGER.df is None:
        return "❌ Error: Sales database file is not loaded or not found. Please ask the Admin to run the pipeline first."
        
    print(f"\nProcessing user query: '{query_text}'")
    
    # 1. Detect Depot
    depot = extract_depot_with_ai(query_text)
    print(f"  Depot detected: {depot}")
    
    # 2. Get markets list for this depot
    mpo_list = DATA_MANAGER.get_mpo_list_for_depot(depot)
    
    # 3. Extract details using AI with MPO context
    intent = extract_details_with_context = extract_query_intent(query_text, depot, mpo_list)
    print(f"  Extracted Intent: {json.dumps(intent)}")
    
    month = intent.get("month")
    product_brand = intent.get("product_brand")
    mpo_code = intent.get("mpo_code")
    customer_name = intent.get("customer_name")
    
    # 4. Filter DataFrame
    filtered_df = DATA_MANAGER.df.copy()
    
    if depot:
        filtered_df = filtered_df[filtered_df['Depot'].str.upper() == depot.upper()]
    if month:
        filtered_df = filtered_df[filtered_df['Month'] == month]
    if product_brand:
        filtered_df = filtered_df[filtered_df['Product_Name'].str.contains(product_brand, case=False, na=False)]
    if mpo_code:
        filtered_df = filtered_df[filtered_df['MPO_Code'].str.upper() == mpo_code.upper()]
    if customer_name:
        filtered_df = filtered_df[filtered_df['Customer_Name'].str.contains(customer_name, case=False, na=False)]
        
    if filtered_df.empty:
        # Build friendly empty-result message
        filters = []
        if depot: filters.append(f"Depot: {depot}")
        if month: filters.append(f"Month: {month}")
        if product_brand: filters.append(f"Product: {product_brand}")
        if mpo_code: filters.append(f"MPO: {mpo_code}")
        if customer_name: filters.append(f"Customer: {customer_name}")
        
        filter_str = ", ".join(filters) if filters else "No filters"
        return f"⚠️ *No records found matching your query.*\n\n*Applied Filters:* {filter_str}\n\nPlease verify your query details and try again."

    # 5. Calculate statistics
    total_qty = filtered_df['Quantity'].sum()
    total_amount = filtered_df['Line_Amount'].sum()
    invoices = filtered_df['Invoice_No'].nunique()
    customers = filtered_df['Customer_ID'].nunique()
    
    # Map MPO Code to Market name for display
    market_display = None
    if mpo_code and DATA_MANAGER.df_mpo is not None:
        mpo_match = DATA_MANAGER.df_mpo[
            (DATA_MANAGER.df_mpo['MPO CODE'].str.upper() == mpo_code.upper()) &
            (DATA_MANAGER.df_mpo['DEPOT'].str.upper() == (depot or "").upper())
        ]
        if not mpo_match.empty:
            market_display = mpo_match.iloc[0]['MARKET']
            
    # Format month name for display
    month_display = month
    if month:
        try:
            dt = datetime.strptime(month, "%Y-%m")
            month_display = dt.strftime("%B %Y")
        except:
            pass

    # Build response Markdown message
    msg_lines = [
        "📊 *SALES REPORT SUMMARY*",
        "=========================================",
        f"🔍 *Query:* \"{query_text}\"",
        "",
        "📍 *Filter Details:*",
        f"▪️ *Depot:* {depot or 'ALL'}"
    ]
    
    if mpo_code:
        mpo_info = f"{mpo_code}"
        if market_display:
            mpo_info += f" ({market_display})"
        msg_lines.append(f"▪️ *Market/MPO:* {mpo_info}")
        
    if month_display:
        msg_lines.append(f"▪️ *Month:* {month_display}")
        
    if product_brand:
        msg_lines.append(f"▪️ *Product:* {product_brand}")
        
    if customer_name:
        msg_lines.append(f"▪️ *Customer:* {customer_name}")
        
    msg_lines.extend([
        "",
        "📈 *Calculated Statistics:*",
        f"▪️ *Total Box Sold:* *{total_qty:,.2f}*",
        f"▪️ *Total Net Sales:* *{total_amount:,.2f} TK*",
        f"▪️ *Total Invoices:* *{invoices:,}*",
        f"▪️ *Unique Customers:* *{customers:,}*",
        "========================================="
    ])
    
    return "\n".join(msg_lines)

# ══════════════════════════════════════════════════════════════════
#  Telegram Bot Core & Long Polling Loop
# ══════════════════════════════════════════════════════════════════

def send_telegram_message(chat_id, text):
    url = f"https://api.telegram.org/bot{TELEGRAM_BOT_TOKEN}/sendMessage"
    payload = {
        "chat_id": chat_id,
        "text": text,
        "parse_mode": "Markdown"
    }
    try:
        r = requests.post(url, json=payload, timeout=15)
        r.raise_for_status()
    except Exception as e:
        print(f"❌ Error sending message to {chat_id}: {e}")

def handle_start_command(chat_id):
    welcome_text = """👋 *Hello! I am the Alco Pharma Sales Query Bot.*

I can query the latest sales transaction report generated by the Admin and give you quick stats on demand.

ℹ️ *What you can ask me (Bangla or English):*
▪️ "january maase Bariahsal 1 Market e alagra koto box sale hoise"
▪️ "chattogram depot e may maase mokast koto invoice aar customer cilo"
▪️ "B001 mpo code er alagra total sales amount koto"
▪️ "Napa product er total sale koto"

Just type your question below! 👇"""
    send_telegram_message(chat_id, welcome_text)

def main_loop():
    print("=" * 80)
    print("  TELEGRAM SALES QUERY BOT - RUNNING (LONG POLLING)")
    print("=" * 80)
    print(f"Bot Token: {TELEGRAM_BOT_TOKEN[:15]}...")
    if DATA_MANAGER.loaded_csv_path:
        print(f"Active Data File: {os.path.basename(DATA_MANAGER.loaded_csv_path)}")
    else:
        print("Active Data File: None (waiting for file generation)")
    print("Bot is listening for messages... Press Ctrl+C to exit.\n")
    
    offset = None
    
    while True:
        try:
            url = f"https://api.telegram.org/bot{TELEGRAM_BOT_TOKEN}/getUpdates"
            params = {"timeout": 30}
            if offset:
                params["offset"] = offset
                
            response = requests.get(url, params=params, timeout=35)
            if response.status_code != 200:
                print(f"⚠ Telegram API returned status {response.status_code}. Retrying...")
                time.sleep(5)
                continue
                
            updates = response.json().get("result", [])
            
            for update in updates:
                offset = update["update_id"] + 1
                
                if "message" not in update:
                    continue
                    
                message = update["message"]
                chat_id = message["chat"]["id"]
                user_info = message["chat"].get("username") or message["chat"].get("first_name") or "User"
                
                if "text" not in message:
                    continue
                    
                text = message["text"].strip()
                print(f"📩 Received message from {user_info} ({chat_id}): '{text}'")
                
                # Check for commands
                if text.startswith("/start") or text.startswith("/help"):
                    handle_start_command(chat_id)
                    continue
                
                # Process query
                send_telegram_message(chat_id, "⏳ *Processing your query... please wait.*")
                
                try:
                    response_text = process_sales_query(text)
                except Exception as ex:
                    print(f"❌ Error processing query: {ex}")
                    response_text = "❌ *An error occurred while processing your query.* Please make sure the query format is correct."
                    
                send_telegram_message(chat_id, response_text)
                print(f"📤 Sent reply to {user_info} ({chat_id})")
                
        except KeyboardInterrupt:
            print("\nShutting down bot...")
            break
        except Exception as e:
            print(f"⚠ Loop Error: {e}")
            time.sleep(5)

if __name__ == "__main__":
    main_loop()
